name: Build Amira APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install platform dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache git libffi-dev libssl-dev libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav libgstreamer-plugins-base1.0-dev libasound2-dev acl

      - name: Build with Buildozer
        uses: ArtemGovorov/buildozer-action@v1.4.1
        with:
          command: buildozer -v android debug
          buildozer_version: stable
          accept_android_licenses: true

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Amira-APK
          path: bin/*.apk
